# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:

version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/php/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/java/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/python/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"