pull_request_rules:
  - name: Dependabot
    conditions:
      - "status-success=php"
      - "status-success=python"
      - "status-success=java"
      - base=master
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        strict: smart+fasttrack
        method: merge