name: CI

on:
  push:
  pull_request:

jobs:
  java:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 15
        check-latest: true
    - run: ( cd java && chmod +x gradlew )
    - run: ( cd java && ./gradlew clean build )
    - run: ( cd java && ./gradlew pitest )
  php:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - run: ( cd php && composer install --prefer-dist --no-progress --no-suggest )
    - run: ( cd php && ./vendor/bin/phpunit --testdox --color=auto )
    - run: ( cd php && phpdbg -qrr ./vendor/bin/infection run ; cat infection.log)
  python:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9.*
        architecture: x64
    - uses: abatilo/actions-poetry@v2.1.1
    - run: ( cd python && poetry install )
    - run: ( cd python && poetry run mut.py -c -e -m --runner pytest -t bowling_game
        -u test_bowling_game --report-html html ; ls html  )
