name: PHP

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - run: ( cd php && composer install --prefer-dist --no-progress --no-suggest )
    - run: ( cd php && ./vendor/bin/phpunit --testdox --color=auto )
    - run: ( cd php && phpdbg -qrr ./vendor/bin/infection run ; cat infection.log)
