
name: Python

on:
  schedule:
    - cron:  '0 12 * * 1-5'
  push: ~
  pull_request: ~

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9.*'
        architecture: 'x64'
    - uses: abatilo/actions-poetry@v2.1.0
    - run: ( cd python && poetry install )
    - run: ( cd python && poetry run mut.py -c -e -m --runner pytest -t bowling_game -u test_bowling_game --report-html html ; ls html  )
