name: Python

on:
  push:
    paths:
      - .github/workflows/python.yml
      - ./python/*

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.9.*
        architecture: x64

    - uses: abatilo/actions-poetry@v2.3.0

    - name: Install Dependencies
      working-directory: python
      run: poetry install

    - name: Run Mutation Tests
      working-directory: python
      run: (poetry run mutmut run --paths-to-mutate=bowling_game.py --runner "python -m pytest" || true) ; poetry run mutmut html ; ls html
